### PR TITLE
docs: restructure README intro

### PR DESCRIPTION
**Pull request by davidlougheed**

### CODE REVIEW

**Comment by brouillette** [comment]
Perhaps we may want to merge this to a release branch

**Review by v-rocheleau — COMMENTED** [review]
The README still has some mentions of bentov2, but a lot of them are for env variables and domain names. Would that be in another PR or do we do the whole switch here?

**Comment by davidlougheed** [comment]
just cosmetic mentions for now i think.

**Review by v-rocheleau — APPROVED** [review]
lgtm

**Pull request merged**
